[package]
name = "brace-hook"
version = "0.1.0"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
description = "Hook discovery for dynamic codebases."
repository = "https://github.com/brace-rs/brace-hook"
license = "MIT OR Apache-2.0"
edition = "2018"

[dev-dependencies]
paste = "0.1"
